workspace:
  base: /go
  path: src/github.com/hehua2018/drone

pipeline:
  build:
    image: golang:1.9
    commands:
      - pwd
      - go env
      - go version
      - go build
      - date

  publish:
      image: plugins/docker
      registry: https://index.docker.io/v1/ 
      repo: hexiaoshi520/golang_base 
      secrets: [ docker_username, docker_password ]
      tags: ${DRONE_TAG}
      when:
        event: tag


  deploy:
      image: appleboy/drone-ssh
      host: dwit.dns05.com
      username: root
      port: 22
      secrets: [ ssh_key ]
      script:
        - cd /opt/gogscicd
        - docker pull nginx 
        - docker run --name nginx -p 80:80 -d nginx 
